include_random_model: True
max_works: -1
experiment_tests: False # change to false, when finished the simulation
experiments:
    rp_init: &rp_init -1
    rp_final: &rp_final 0  # 70 # 36
    rp_stop_init: *rp_init
    rp_stop_final: *rp_final

correlation_method: spearman

results:
    filepath: results

outputs:
    init_values: 1
    simulation_random:
        filepath: simulation_dataset
        data_filepath: "{}"
    simulation_random_avg_response:
        filepath: simulation_dataset_avg_response
        data_filepath: "{}"
    extension_type: .csv
    extension_local_img: .png
    extension_best_img: .eps
    args:
        dpi: 300

generation_params:
    aniso:
        rotation:
            - [0.6, -0.6]
            - [-0.4, 0.8]
    noisy_circles:
        factor: 0.5
        noise: &noisy 0.05
    noisy_moons:
        noise: *noisy
    blobs:
        random_state: 8
    varied:
        cluster_std:
            - 1.0
            - 2.5
            - 0.5
    no_structure:
        - 1000
        - 2

beta_params:
    learning_rate: 0.1
    epochs: 10000 # 10000
    n_inits: 1000 # 1000
    # n_workers: -1,
    random_seed: 1
    tol: 1.0e-8
    set_priors: True

datasets:
    - iris
    - wine
    - breast_cancer
    - aniso
    - blobs
    - varied
    - noisy_moons
    - noisy_circles
    - no_structure

#     - digits

models_fit:
    - kmeans
    - dbscan
    - kernel_kmeans
    - spectral_clustering
    - mean_shift
    - optics

general:
    min: &min 1
    max: &max 9
    step: 1
    random_state: &random_state 0

models:
    kmeans:
    dbscan:
        eps:
            min: &min_dbscan 0.1
            max: *min
            step: *min_dbscan
        min_samples: 2
    kernel_kmeans:
        kernel: gak
        random_state: *random_state
    spectral_clustering:
        eigen_solver: arpack
        affinity: nearest_neighbors
    mean_shift:
        - &none_args {}
    optics:
        - *none_args
